version: 2
sphinx:
  configuration: docs/source/conf.py

# Build all formats
formats:
  - epub

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements-test.txt
    - method: pip
      path: .
